 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

module EnjuIr
  RSpec.describe "/enju_ir/filesets", type: :request do
    # Fileset. As you add validations to Fileset, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) {
      skip("Add a hash of attributes valid for your model")
    }

    let(:invalid_attributes) {
      skip("Add a hash of attributes invalid for your model")
    }

    describe "GET /index" do
      it "renders a successful response" do
        Fileset.create! valid_attributes
        get enju_ir.filesets_url
        expect(response).to be_successful
      end
    end

    describe "GET /show" do
      it "renders a successful response" do
        fileset = Fileset.create! valid_attributes
        get enju_ir.fileset_url(fileset)
        expect(response).to be_successful
      end
    end

    describe "GET /new" do
      it "renders a successful response" do
        get enju_ir.new_fileset_url
        expect(response).to be_successful
      end
    end

    describe "GET /edit" do
      it "render a successful response" do
        fileset = Fileset.create! valid_attributes
        get edit_fileset_url(fileset)
        expect(response).to be_successful
      end
    end

    describe "POST /create" do
      context "with valid parameters" do
        it "creates a new Fileset" do
          expect {
            post enju_ir.filesets_url, params: { fileset: valid_attributes }
          }.to change(Fileset, :count).by(1)
        end

        it "redirects to the created fileset" do
          post enju_ir.filesets_url, params: { fileset: valid_attributes }
          expect(response).to redirect_to(fileset_url(Fileset.last))
        end
      end

      context "with invalid parameters" do
        it "does not create a new Fileset" do
          expect {
            post enju_ir.filesets_url, params: { fileset: invalid_attributes }
          }.to change(Fileset, :count).by(0)
        end

        it "renders a successful response (i.e. to display the 'new' template)" do
          post enju_ir.filesets_url, params: { fileset: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    describe "PATCH /update" do
      context "with valid parameters" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        it "updates the requested fileset" do
          fileset = Fileset.create! valid_attributes
          patch fileset_url(fileset), params: { fileset: new_attributes }
          fileset.reload
          skip("Add assertions for updated state")
        end

        it "redirects to the fileset" do
          fileset = Fileset.create! valid_attributes
          patch fileset_url(fileset), params: { fileset: new_attributes }
          fileset.reload
          expect(response).to redirect_to(fileset_url(fileset))
        end
      end

      context "with invalid parameters" do
        it "renders a successful response (i.e. to display the 'edit' template)" do
          fileset = Fileset.create! valid_attributes
          patch fileset_url(fileset), params: { fileset: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    describe "DELETE /destroy" do
      it "destroys the requested fileset" do
        fileset = Fileset.create! valid_attributes
        expect {
          delete fileset_url(fileset)
        }.to change(Fileset, :count).by(-1)
      end

      it "redirects to the filesets list" do
        fileset = Fileset.create! valid_attributes
        delete fileset_url(fileset)
        expect(response).to redirect_to(filesets_url)
      end
    end
  end
end
